# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yavor Georgiev's Blog
email: yavor.georgiev@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to Yavor Georgiev's blog. Yavor is a Product Manager at goextend.io, a startup 
  that makes in-product extensibility and integrations painless for SaaS developers. 
  Previously at Hulu and Microsoft Azure. 
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: YavorGeorgiev
github_username:  yavorg
permalink: /posts/:year/:month/:day/:title

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
